server:
  port: 8080
spring:
  application:
    name: bally's challenge
  profiles:
    active: dev
  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/sample
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sample
    username: sample
    password: sample
  jpa:
    hibernate:
     ddl-auto: none
    show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    enabled: true
